spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
jwt:
  secret-key: ZGtyb3doZmZsZWtka3Jvd2hmZmxla2Rrcm93aGZmbGVrZGtyb3doZmZsZWtka3Jvd2hmZmxla2Rrcm93aGZmbGVrZGtyb3doZmZsZWtka3Jvd2hmZmxlaw==
